# Generated by Django 4.0.6 on 2022-07-26 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('is_staff', models.BooleanField(default=False, verbose_name='کارمند؟')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین؟')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام خانوادگی')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='نام کاربری')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('age', models.CharField(blank=True, max_length=3, null=True, verbose_name='سن')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('registered_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت نام')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='عکس')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='کپشن')),
                ('view', models.PositiveIntegerField(default=0, verbose_name='بازدید')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='ویدیو')),
                ('category', models.ManyToManyField(related_name='post_category', to='api.category')),
                ('like', models.ManyToManyField(related_name='user_liked', to=settings.AUTH_USER_MODEL, verbose_name='لایک')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='صاحب پست')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
            },
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.ManyToManyField(related_name='user_followers', to=settings.AUTH_USER_MODEL, verbose_name='دنبال کننده ها')),
                ('following', models.ManyToManyField(related_name='user_following', to=settings.AUTH_USER_MODEL, verbose_name='دنبال شونده ها')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دنبال کننده و دنبال شونده',
                'verbose_name_plural': 'دنبال کننده ها و دنبال شونده ها',
            },
        ),
    ]
