# Generated by Django 4.0.6 on 2022-07-26 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='like',
            field=models.ManyToManyField(null=True, related_name='user_liked', to=settings.AUTH_USER_MODEL, verbose_name='لایک'),
        ),
    ]
