# Generated by Django 4.0.6 on 2022-07-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_posts_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AddField(
            model_name='posts',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-08-05T07:35:20Z', verbose_name='تاریخ تغییر'),
            preserve_default=False,
        ),
    ]
