# Generated by Django 4.1 on 2022-08-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_posts_created_at_posts_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles-images/', verbose_name='عکس پروفایل'),
        ),
    ]
