# Generated by Django 4.1 on 2022-08-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='بیوگرافی'),
        ),
    ]
